name: docker-build-and-publish

on:
  push:
    branches:
      - 'master'

jobs:
  release:
    name: Create Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Get commit Hash
        id: commit
        uses: pr-mpt/actions-commit-hash@v1
      - name: Checkout
        uses: actions/checkout@v2
      -
        name: Zip
        uses: vimtor/action-zip@v1
        with:
          recursive: true
          files: ./*
          dest: challenges.zip
      -
        name: Create Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "challenges.tar.gz"
          commit: 'master'
          tag: "${{ steps.commit.outputs.short }}"